Repository linode/linode-cloud-controller-manager, pull requests merged in 2024-11, with the labels that each got.

#241 manage routes for instances in multiple vpcs in a single region
  README.md
  cloud/linode/cloud.go
  cloud/linode/instances.go
  cloud/linode/route_controller.go
  cloud/linode/route_controller_test.go
  cloud/linode/vpc.go
  deploy/chart/templates/daemonset.yaml
  deploy/chart/values.yaml
  main.go
Labels: enhancement

#245 [fix] : fix expired cert for e2e tests
  e2e/test/certificates/server.crt
  e2e/test/certificates/server.csr
  e2e/test/framework/secret.go
Labels: bugfix

#246 create ip holder per cluster + tests, update docs
  README.md
  cloud/linode/cilium_loadbalancers.go
  cloud/linode/cilium_loadbalancers_test.go
  cloud/linode/cloud.go
  cloud/linode/common.go
  cloud/linode/loadbalancers.go
  deploy/chart/templates/daemonset.yaml
  deploy/chart/values.yaml
  go.mod
  go.sum
  main.go
Labels: added-feature

#248 [repo-ci-improvement] : update GHA to run e2e tests
  .github/filters.yml
  .github/workflows/ci.yml
  Makefile
  cloud/linode/cloud.go
  devbox.json
  e2e/setup/ctlptl-config.yaml
  main.go
Labels: repo-ci-improvement
