Repository linode/linode-cloud-controller-manager, pull requests merged in 2024-06, with the labels that each got.

#208 [feat] - add support for cilium-backed loadbalancers
  README.md
  cloud/annotations/annotations.go
  cloud/linode/cilium_loadbalancers.go
  cloud/linode/cilium_loadbalancers_test.go
  cloud/linode/client/client.go
  cloud/linode/client/mocks/mock_client.go
  cloud/linode/cloud.go
  cloud/linode/common.go
  cloud/linode/common_test.go
  cloud/linode/loadbalancers.go
  cloud/linode/loadbalancers_test.go
  deploy/chart/templates/clusterrole-rbac.yaml
  deploy/chart/templates/daemonset.yaml
  deploy/chart/values.yaml
  go.mod
  go.sum
  main.go
Labels: added-feature

#214 fix: remove firewall device by device ID not entity ID
  cloud/linode/firewall/firewalls.go
  cloud/linode/loadbalancers_test.go
Labels: bug, bugfix

#215 [fix] don't try to share IPs that may have been removed on the ip-holder outside of the CCM logic
  cloud/linode/cilium_loadbalancers.go
  cloud/linode/cilium_loadbalancers_test.go
Labels: bugfix

#219 add timeout for linodego http client
  README.md
  cloud/linode/client/client.go
  cloud/linode/cloud.go
Labels: bugfix
