Repository linode/linode-cloud-controller-manager, pull requests merged in 2025-01, with the labels that each got.

#287 [test] : fix random failures in e2e tests due to curl error
  e2e/test/fw-use-specified-nb/chainsaw-test.yaml
  e2e/test/lb-http-body-health-check/chainsaw-test.yaml
  e2e/test/lb-http-status-health-check/chainsaw-test.yaml
  e2e/test/lb-passive-health-check/chainsaw-test.yaml
  e2e/test/lb-tcp-connection-health-check/chainsaw-test.yaml
  e2e/test/lb-with-http-to-https/chainsaw-test.yaml
  e2e/test/lb-with-multiple-http-https-ports/chainsaw-test.yaml
  e2e/test/lb-with-node-addition/chainsaw-test.yaml
Labels: testing

#286 [test] : add more unittests to increase code-coverage
  cloud/linode/cloud_test.go
  cloud/linode/node_controller_test.go
  cloud/linode/service_controller_test.go
  codecov.yml
Labels: testing

#277 [feat] add support for custom BGP environment overrides via environment variables
  README.md
  cloud/linode/cilium_loadbalancers.go
  cloud/linode/cilium_loadbalancers_test.go
Labels: new-feature

#289 [fix] : ignore if env vars are empty
  cloud/linode/cilium_loadbalancers.go
Labels: bugfix

#290 [test] Add Cilium BGP LB e2e test
  .github/workflows/ci.yml
  Makefile
  devbox.json
  e2e/bgp-test/lb-cilium-bgp/chainsaw-test.yaml
  e2e/bgp-test/lb-cilium-bgp/create-pod-service.yaml
  e2e/setup/cilium-setup.sh
Labels: testing

#294 [test] Add unit test cases for Sentry
  Makefile
  sentry/sentry_test.go
Labels: testing

#298 [docs] refactor/organizing docs
  .github/filters.yml
  README.md
  _config.yaml
  docs/configuration/README.md
  docs/configuration/annotations.md
  docs/configuration/environment.md
  docs/configuration/firewall.md
  docs/configuration/loadbalancer.md
  docs/configuration/nodes.md
  docs/configuration/routes.md
  docs/configuration/session-affinity.md
  docs/development/README.md
  docs/examples/README.md
  docs/examples/advanced.md
  docs/examples/basic.md
  docs/getting-started/README.md
  docs/getting-started/helm-installation.md
  docs/getting-started/installation.md
  docs/getting-started/manual-installation.md
  docs/getting-started/overview.md
  docs/getting-started/requirements.md
  docs/getting-started/troubleshooting.md
  docs/getting-started/verification.md
Labels: documentation

#306 [fix] : fix ACL update bug
  cloud/linode/firewall/firewalls.go
  cloud/linode/loadbalancers_test.go
  e2e/test/lb-fw-update-acl/chainsaw-test.yaml
  e2e/test/lb-fw-update-acl/create-pods-services.yaml
  e2e/test/lb-fw-update-acl/update-service.yaml
Labels: bugfix

#296 [feat] add linode token health check
  cloud/linode/client/client.go
  cloud/linode/client/mocks/mock_client.go
  cloud/linode/cloud.go
  cloud/linode/health_check.go
  cloud/linode/health_check_test.go
  deploy/chart/templates/daemonset.yaml
  deploy/chart/values.yaml
  main.go
Labels: new-feature

#307 [fix] : delete fw if provisioned by CCM with ACL
  cloud/linode/firewall/firewalls.go
  cloud/linode/loadbalancers.go
  e2e/test/lb-fw-delete-acl/chainsaw-test.yaml
  e2e/test/lb-fw-delete-acl/create-pods-services.yaml
Labels: bugfix
