Repository linode/linode-cloud-controller-manager, pull requests merged in 2025-07, with the labels that each got.

#409 [CI] Update index.yaml
  index.yaml
Labels: repo-ci-improvement

#410 [fix] : use updated service status as upstream controller can pass wrong info
  cloud/linode/loadbalancers.go
  cloud/linode/loadbalancers_test.go
  e2e/test/lb-with-node-addition/chainsaw-test.yaml
Labels: bugfix

#416 [CI] : allow all githubusercontent.com urls
  .github/workflows/build-test.yml
  .github/workflows/ci.yml
Labels: repo-ci-improvement

#414 [feat]: Add custom prefix for load balancer
  cloud/linode/cloud.go
  cloud/linode/cloud_test.go
  cloud/linode/loadbalancers.go
  deploy/chart/templates/daemonset.yaml
  deploy/chart/values.yaml
  docs/configuration/environment.md
  main.go
Labels: new-feature

#417 [improvement] : remove deprecated vpcname flag
  cloud/linode/cloud.go
  cloud/linode/cloud_test.go
  deploy/chart/templates/daemonset.yaml
  deploy/chart/values.yaml
  main.go
Labels: improvement

#369 [feat] : add ipv6 ipam to CCM
  Makefile
  cloud/linode/client/client.go
  cloud/linode/client/client_with_metrics.go
  cloud/linode/client/mocks/mock_client.go
  cloud/linode/cloud.go
  cloud/linode/cloud_test.go
  cloud/linode/nodeipamcontroller.go
  cloud/linode/nodeipamcontroller_test.go
  cloud/nodeipam/doc.go
  cloud/nodeipam/ipam/cidr_allocator.go
  cloud/nodeipam/ipam/cloud_allocator.go
  cloud/nodeipam/ipam/cloud_allocator_test.go
  cloud/nodeipam/ipam/controller_test.go
  cloud/nodeipam/ipam/doc.go
  cloud/nodeipam/node_ipam_controller.go
  deploy/chart/templates/daemonset.yaml
  deploy/chart/values.yaml
  docs/configuration/environment.md
  docs/configuration/nodeipam.md
  go.mod
  go.sum
  main.go
Labels: new-feature
