Repository linode/linode-cloud-controller-manager, pull requests merged in 2025-04, with the labels that each got.

#363 [CI] Add nightly merge workflow for gh-pages
  .github/workflows/nightly-merge.yml
Labels: repo-ci-improvement

#366 [feat] : enable nodeipamcontroller within CCM
  README.md
  cloud/linode/cloud.go
  cloud/linode/nodeipamcontroller.go
  cloud/linode/nodeipamcontroller_test.go
  deploy/chart/templates/daemonset.yaml
  deploy/chart/values.yaml
  docs/configuration/environment.md
  docs/configuration/nodeipam.md
  go.mod
  go.sum
  main.go
Labels: new-feature

#368 [fix] Ignore ipv6 routes
  cloud/linode/route_controller.go
  cloud/linode/route_controller_test.go
Labels: bugfix

#374 [CI] : add logs for e2e tests for easier debugging
  e2e/test/lb-http-body-health-check/chainsaw-test.yaml
  e2e/test/lb-http-status-health-check/chainsaw-test.yaml
  e2e/test/lb-passive-health-check/chainsaw-test.yaml
  e2e/test/lb-tcp-connection-health-check/chainsaw-test.yaml
  e2e/test/lb-updated-with-nb-id/chainsaw-test.yaml
  e2e/test/lb-with-http-to-https/chainsaw-test.yaml
  e2e/test/lb-with-multiple-http-https-ports/chainsaw-test.yaml
  e2e/test/lb-with-node-addition/chainsaw-test.yaml
Labels: repo-ci-improvement

#375 [CI] : increase retries count for node-addition test
  e2e/test/lb-http-body-health-check/chainsaw-test.yaml
  e2e/test/lb-http-status-health-check/chainsaw-test.yaml
  e2e/test/lb-passive-health-check/chainsaw-test.yaml
  e2e/test/lb-tcp-connection-health-check/chainsaw-test.yaml
  e2e/test/lb-updated-with-nb-id/chainsaw-test.yaml
  e2e/test/lb-with-multiple-http-https-ports/chainsaw-test.yaml
  e2e/test/lb-with-node-addition/chainsaw-test.yaml
Labels: repo-ci-improvement

#370 [improvement] Refactor code blocks ignored by errorlint
  cloud/linode/loadbalancers.go
  cloud/linode/node_controller.go
  cloud/linode/service_controller.go
Labels: improvement
