Repository linode/linode-cloud-controller-manager, pull requests merged in 2025-02, with the labels that each got.

#314 [CI] : use pull_request_target for CI workflows
  .github/workflows/ci.yml
Labels: repo-ci-improvement

#318 [improvement] set securityContext and use affinity instead of nodeSelector
  deploy/ccm-linode-template.yaml
  deploy/chart/templates/daemonset.yaml
  deploy/chart/values.yaml
Labels: improvement

#321 [fix] : limit fw-rule description to 100 chars
  cloud/linode/firewall/firewalls.go
  cloud/linode/loadbalancers_test.go
Labels: bugfix

#330 [CI] : allow golangci-lint.run url
  .github/workflows/ci.yml
Labels: repo-ci-improvement

#329 [test] : add ccm resource check as separate test
  e2e/test/ccm-resources/chainsaw-test.yaml
  e2e/test/fw-use-specified-nb/chainsaw-test.yaml
  e2e/test/lb-created-with-new-nb-id/chainsaw-test.yaml
  e2e/test/lb-created-with-specified-nb-id/chainsaw-test.yaml
  e2e/test/lb-delete-svc-no-nb/chainsaw-test.yaml
  e2e/test/lb-delete-svc-use-new-nbid/chainsaw-test.yaml
  e2e/test/lb-delete-svc-use-specified-nb/chainsaw-test.yaml
  e2e/test/lb-fw-delete-acl/chainsaw-test.yaml
  e2e/test/lb-fw-update-acl/chainsaw-test.yaml
  e2e/test/lb-hostname-only-ingress/chainsaw-test.yaml
  e2e/test/lb-http-body-health-check/chainsaw-test.yaml
  e2e/test/lb-http-status-health-check/chainsaw-test.yaml
  e2e/test/lb-passive-health-check/chainsaw-test.yaml
  e2e/test/lb-preserve-annotation-new-nb-specified/chainsaw-test.yaml
  e2e/test/lb-preserve-annotation-svc-delete/chainsaw-test.yaml
  e2e/test/lb-simple/chainsaw-test.yaml
  e2e/test/lb-single-tls/chainsaw-test.yaml
  e2e/test/lb-tcp-connection-health-check/chainsaw-test.yaml
  e2e/test/lb-updated-with-nb-id/chainsaw-test.yaml
  e2e/test/lb-with-http-to-https/chainsaw-test.yaml
  e2e/test/lb-with-multiple-http-https-ports/chainsaw-test.yaml
  e2e/test/lb-with-node-addition/chainsaw-test.yaml
  e2e/test/lb-with-proxyprotocol-default-annotation/chainsaw-test.yaml
  e2e/test/lb-with-proxyprotocol-override/chainsaw-test.yaml
  e2e/test/lb-with-proxyprotocol-port-specific/chainsaw-test.yaml
  e2e/test/lb-with-proxyprotocol-set/chainsaw-test.yaml
  e2e/test/route-controller-test/chainsaw-test.yaml
Labels: testing

#331 [CI] : fix image used by ci and concurrency of gha runs
  .github/workflows/ci.yml
Labels: repo-ci-improvement

#332 [improvement] Allow setting vpcName(s) without enabling route controller
  deploy/chart/templates/daemonset.yaml
  deploy/chart/values.yaml
  docs/getting-started/helm-installation.md
Labels: improvement

#328 [improvement] Add subnet filtering for routes management
  cloud/linode/client/client.go
  cloud/linode/client/client_with_metrics.go
  cloud/linode/client/mocks/mock_client.go
  cloud/linode/cloud.go
  cloud/linode/vpc.go
  cloud/linode/vpc_test.go
  deploy/chart/templates/daemonset.yaml
  deploy/chart/values.yaml
  main.go
Labels: improvement

#334 [CI] : move steps which don't require secrets to separate workflow
  .github/workflows/build-test.yml
  .github/workflows/ci.yml
Labels: repo-ci-improvement

#336 [test] : add labels to run e2e tests
  Makefile
  e2e/bgp-test/lb-cilium-bgp/chainsaw-test.yaml
  e2e/test/ccm-resources/chainsaw-test.yaml
  e2e/test/fw-use-specified-nb/chainsaw-test.yaml
  e2e/test/lb-created-with-new-nb-id/chainsaw-test.yaml
  e2e/test/lb-created-with-specified-nb-id/chainsaw-test.yaml
  e2e/test/lb-delete-svc-no-nb/chainsaw-test.yaml
  e2e/test/lb-delete-svc-use-new-nbid/chainsaw-test.yaml
  e2e/test/lb-delete-svc-use-specified-nb/chainsaw-test.yaml
  e2e/test/lb-fw-delete-acl/chainsaw-test.yaml
  e2e/test/lb-fw-update-acl/chainsaw-test.yaml
  e2e/test/lb-hostname-only-ingress/chainsaw-test.yaml
  e2e/test/lb-http-body-health-check/chainsaw-test.yaml
  e2e/test/lb-http-status-health-check/chainsaw-test.yaml
  e2e/test/lb-passive-health-check/chainsaw-test.yaml
  e2e/test/lb-preserve-annotation-new-nb-specified/chainsaw-test.yaml
  e2e/test/lb-preserve-annotation-svc-delete/chainsaw-test.yaml
  e2e/test/lb-simple/chainsaw-test.yaml
  e2e/test/lb-single-tls/chainsaw-test.yaml
  e2e/test/lb-tcp-connection-health-check/chainsaw-test.yaml
  e2e/test/lb-updated-with-nb-id/chainsaw-test.yaml
  e2e/test/lb-with-http-to-https/chainsaw-test.yaml
  e2e/test/lb-with-multiple-http-https-ports/chainsaw-test.yaml
  e2e/test/lb-with-node-addition/chainsaw-test.yaml
  e2e/test/lb-with-proxyprotocol-default-annotation/chainsaw-test.yaml
  e2e/test/lb-with-proxyprotocol-override/chainsaw-test.yaml
  e2e/test/lb-with-proxyprotocol-port-specific/chainsaw-test.yaml
  e2e/test/lb-with-proxyprotocol-set/chainsaw-test.yaml
  e2e/test/route-controller-test/chainsaw-test.yaml
Labels: testing
