Repository linode/linode-cloud-controller-manager, pull requests merged in 2025-03, with the labels that each got.

#316 [feat] add support for different nodebalancer types
  cloud/annotations/annotations.go
  cloud/linode/cloud.go
  cloud/linode/loadbalancers.go
  cloud/linode/loadbalancers_test.go
  deploy/chart/templates/daemonset.yaml
  deploy/chart/values.yaml
  docs/configuration/annotations.md
  e2e/test/lb-premium-nb/chainsaw-test.yaml
  e2e/test/lb-premium-nb/create-pods-services.yaml
  go.mod
  go.sum
  main.go
Labels: new-feature

#337 [feat] : add support for configuring nodebalancers with VPC
  Makefile
  cloud/annotations/annotations.go
  cloud/linode/fake_linode_test.go
  cloud/linode/loadbalancers.go
  cloud/linode/loadbalancers_test.go
  docs/configuration/annotations.md
  docs/configuration/loadbalancer.md
  e2e/test/lb-with-vpc-backends/chainsaw-test.yaml
  e2e/test/lb-with-vpc-backends/create-pods-services.yaml
  go.mod
  go.sum
  main.go
Labels: new-feature

#339 [feat] Add IPv6 ingress address support for NodeBalancer services
  cloud/annotations/annotations.go
  cloud/linode/cloud.go
  cloud/linode/loadbalancers.go
  cloud/linode/loadbalancers_test.go
  deploy/chart/templates/daemonset.yaml
  deploy/chart/values.yaml
  docs/configuration/README.md
  docs/configuration/annotations.md
  docs/configuration/environment.md
  docs/configuration/loadbalancer.md
  main.go
Labels: new-feature

#342 [improvement] : add flag to set nodebalancer subnet
  cloud/linode/cloud.go
  cloud/linode/loadbalancers.go
  cloud/linode/loadbalancers_test.go
  deploy/chart/templates/daemonset.yaml
  deploy/chart/values.yaml
  docs/configuration/environment.md
  docs/configuration/loadbalancer.md
  main.go
Labels: improvement

#343 [CI] Golangci-lint update part 1
  .golangci.yml
  cloud/linode/cilium_loadbalancers.go
  cloud/linode/cilium_loadbalancers_test.go
  cloud/linode/client/client.go
  cloud/linode/cloud.go
  cloud/linode/cloud_test.go
  cloud/linode/fake_linode_test.go
  cloud/linode/firewall/firewalls.go
  cloud/linode/health_check.go
  cloud/linode/health_check_test.go
  cloud/linode/instances.go
  cloud/linode/instances_test.go
  cloud/linode/loadbalancers.go
  cloud/linode/metrics.go
  cloud/linode/node_controller_test.go
  cloud/linode/service_controller.go
  cloud/linode/service_controller_test.go
  cloud/linode/vpc.go
  cloud/linode/vpc_test.go
  main.go
Labels: repo-ci-improvement

#344 [CI] Golangci-lint update part 2
  .golangci.yml
  cloud/linode/cilium_loadbalancers_test.go
  cloud/linode/instances.go
  cloud/linode/instances_test.go
  cloud/linode/loadbalancers.go
  cloud/linode/loadbalancers_test.go
  cloud/linode/node_controller.go
Labels: repo-ci-improvement

#341 [fix] : use latest node object when processing node update request
  cloud/linode/instances_test.go
  cloud/linode/node_controller.go
  cloud/linode/node_controller_test.go
Labels: bugfix

#349 [CI] Golangci-lint update part 4
  .golangci.yml
  cloud/linode/cilium_loadbalancers.go
  cloud/linode/cilium_loadbalancers_test.go
  cloud/linode/cloud.go
  cloud/linode/cloud_test.go
  cloud/linode/instances.go
  cloud/linode/instances_test.go
  cloud/linode/loadbalancers.go
  cloud/linode/loadbalancers_test.go
  cloud/linode/node_controller.go
  cloud/linode/node_controller_test.go
  cloud/linode/route_controller.go
  cloud/linode/route_controller_test.go
  cloud/linode/service_controller.go
  cloud/linode/service_controller_test.go
  cloud/linode/vpc_test.go
  main.go
  sentry/sentry_test.go
Labels: repo-ci-improvement

#353 [fix] : add k8s node cache and prefer providerID for node search
  cloud/linode/node_controller.go
  cloud/linode/node_controller_test.go
  cloud/linode/route_controller.go
  cloud/linode/route_controller_test.go
  docs/configuration/environment.md
  e2e/test/route-controller-test/chainsaw-test.yaml
Labels: bugfix

#357 [test] Subnet filter testing
  .github/workflows/ci.yml
  Makefile
  devbox.json
  e2e/subnet-test/chainsaw-test.yaml
Labels: testing

#361 [fix] : add context timeout to prevent node_controller for hanging
  cloud/linode/node_controller.go
Labels: bugfix

#360 [docs] : update doc with correct type and note to specify values as string
  docs/configuration/annotations.md
Labels: documentation
