Repository linode/linode-cloud-controller-manager, pull requests merged in 2025-08, with the labels that each got.

#434 [deps] : use upstream linodego instead of forked repo's linodego
  go.mod
  go.sum
Labels: dependencies

#435 [feat] add support for using linode interfaces (beta-only)
  cloud/linode/client/client.go
  cloud/linode/client/client_with_metrics.go
  cloud/linode/client/mocks/mock_client.go
  cloud/linode/route_controller.go
  cloud/linode/route_controller_test.go
  cloud/nodeipam/ipam/cloud_allocator.go
  cloud/nodeipam/ipam/cloud_allocator_test.go
Labels: new-feature

#439 [improvement][feat] Deterministic IPv6 /112 PodCIDR via :0:c::/112; update tests/docs
  cloud/nodeipam/ipam/cloud_allocator.go
  cloud/nodeipam/ipam/cloud_allocator_test.go
  docs/configuration/nodeipam.md
Labels: new-feature, improvement
