Repository linode/linode-cloud-controller-manager, pull requests merged in 2025-05, with the labels that each got.

#382 [deps] Update Go version, golangci, and kubernetes deps
  .github/workflows/build-test.yml
  .golangci.yml
  Makefile
  cloud/linode/loadbalancers.go
  cloud/linode/loadbalancers_test.go
  go.mod
  go.sum
Labels: dependencies

#380 [fix] reconcile NodeBalancer firewall rules on port changes
  cloud/linode/firewall/firewalls.go
  cloud/linode/firewall/firewalls_test.go
  e2e/test/lb-update-port/chainsaw-test.yaml
  e2e/test/lb-update-port/create-pods-services.yaml
  e2e/test/lb-update-port/update-port-service.yaml
Labels: bugfix

#386 [fix]: Fix getNodeBalancerByStatus bug when IPv6 ingress is enabled
  cloud/linode/loadbalancers.go
  cloud/linode/loadbalancers_test.go
Labels: bugfix

#387 [feat] : add support for nodebalancers with UDP ports
  cloud/annotations/annotations.go
  cloud/linode/loadbalancers.go
  cloud/linode/loadbalancers_helpers.go
  cloud/linode/loadbalancers_test.go
  devbox.lock
  docs/configuration/annotations.md
  docs/configuration/loadbalancer.md
  docs/examples/README.md
  docs/examples/basic.md
  e2e/test/lb-with-udp-ports/chainsaw-test.yaml
  e2e/test/lb-with-udp-ports/create-pods-services.yaml
  examples/test.sh
  examples/udp-example.yaml
  go.mod
  go.sum
Labels: new-feature
